#!/bin/bash

sudo fallocate -l 8G /swapfile
#sudo dd if=/dev/zero of=/swapfile bs=1M count=8192
sudo chmod 600 /swapfile
sudo mkswap /swapfile
sudo swapon /swapfile

echo "Remember to add '/swapfile swap swap defaults 0 0' into /etc/fstab"
