#!/bin/bash

# Set up sources.list
sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu \
    $(lsb_release -sc) main" > \
    /etc/apt/sources.list.d/ros-latest.list'

# Set up keys
curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -

# Install ROS
sudo apt update
sudo apt install ros-melodic-desktop-full -y

# Install dependencies for building
sudo apt install python-rosdep python-rosinstall python-rosinstall-generator \
    python-wstool build-essential -y

# Initialize rosdep
sudo apt install python-rosdep -y
sudo rosdep init
rosdep update

echo "Remember to source /opt/ros/noetic/setup.bash"
