#!/bin/bash

git clone git@github.com:Exiv2/exiv2.git

pushd exiv2

mkdir build && pushd build

cmake-gui .

cmake --build

make tests

sudo make install

popd
popd

echo 'Remember to add export PATH="/usr/local/bin:$PATH" and export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH" in ~/.bashrc'
