#!/bin/bash

sudo apt update

sudo apt install ccache vim nano xclip cmake-gui cmake tmux -y

#sudo apt install -y net-tools network-manager

sudo apt purge modemmanager -y

sudo systemctl set-default multi-user
