#!/bin/bash

sudo apt install build-essential cmake git pkg-config libgtk-3-dev \
    libavcodec-dev libavformat-dev libswscale-dev libv4l-dev \
    libxvidcore-dev libx264-dev libjpeg-dev libpng-dev libtiff-dev \
    gfortran openexr libatlas-base-dev python3-dev python3-numpy \
    libtbb2 libtbb-dev libdc1394-22-dev cmake-qt-gui libgdcm-tools \
    libgdal-dev ffmpeg libgstreamer1.0-0 gstreamer1.0-plugins-base \
    gstreamer1.0-plugins-good gstreamer1.0-plugins-bad \
    gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-doc \
    gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl \
    gstreamer1.0-gtk3 gstreamer1.0-qt5 gstreamer1.0-pulseaudio -y
    
sudo apt install build-essential cmake git pkg-config libgtk-3-dev \
    libavcodec-dev libavformat-dev libswscale-dev libv4l-dev \
    libxvidcore-dev libx264-dev libjpeg-dev libpng-dev libtiff-dev \
    gfortran openexr libatlas-base-dev python3-dev python3-numpy \
    libtbb2 libtbb-dev libdc1394-22-dev libopenexr-dev \
    libgstreamer-plugins-base1.0-dev libgstreamer1.0-dev qt5-default -y
    
sudo apt install python-numpy python3-numpy -y

git clone git@github.com:opencv/opencv.git
pushd opencv
git checkout 4.5.3
mkdir build
popd

git clone git@github.com:opencv/opencv_contrib.git
pushd opencv_contrib
git checkout 4.5.3
popd

echo 'Continuing the installation with cmake-gui, as it is easier to control the installation with that'
cd opencv/build
cmake-gui .
make -j$(nproc) -l 4.0
sudo make install
