# This file only contains mapping for mission functions
# This works similarly to enum
uint8 INITIALIZE=0
uint8 ARM_THROTTLE=1
uint8 DISARM_THROTTLE=2
uint8 SET_POS_LOCAL=3
uint8 CHANGE_MODE=4
uint8 WAIT_KEY_PRESS=5
uint8 SAVE_IMG=6
uint8 WAIT_TIME=7
uint8 WAIT_GPS=8
uint8 WAIT_FOREVER=9
uint8 GP_TAKEOFF=10
uint8 TAKEOFF_CUR=11
uint8 GP_LAND=12
uint8 LAND_CUR=13
uint8 GEOTAG=14
uint8 WAIT_WP=15
uint8 WAIT_CAM_TRIG=16
uint8 WAIT_SAVE_IMG=17