#!/bin/bash

# Install robot_startup
sudo apt install ros-noetic-robot-upstart -y

# Install mavros and mavros-extras
sudo apt install ros-noetic-mavros ros-noetic-mavros-extras -y

# image-transport
sudo apt install ros-noetic-image-transport ros-noetic-image-transport-plugins -y

# SDL
sudo apt install -y libsdl1.2-dev libsdl-image1.2-dev

# Eigen3
sudo apt install libeigen3-dev -y

# GDB
sudo apt install gdb -y

# GPIO
sudo apt install rpi.gpio-common -y
sudo adduser "$USER" dialout

# Install gazebo_ros_pkgs
#sudo apt-get install ros-noetic-gazebo-ros-pkgs ros-noetic-gazebo-ros-control -y

# realsense-ros dependency
#sudo apt install ros-noetic-ddynamic-reconfigure -y

# realsense-ros
#sudo apt install ros-noetic-realsense2-camera ros-noetic-realsense2-description -y

# RTABMAP-SLAM
#sudo apt install ros-noetic-rtabmap-ros ros-noetic-rtabmap -y

# Exiv2
#sudo apt install -y exiv2 libexiv2-dev

# MAVProxy
sudo apt install -y python3-dev python3-opencv python3-wxgtk4.0 \
    python3-pip python3-matplotlib python3-lxml python3-pygame
pip3 install PyYAML mavproxy --use
echo "Don't forget to add export PATH=\"\$PATH:\$HOME/.local/bin\" in ~/.bashrc"

# Remove modemmanager, so that mavproxy can be used
sudo apt purge modemmanager -y

# Clone all submodules
git submodule update --init --recursive

# Initialize workspace
#mkdir src
catkin init
wstool init src

# Update workspace
wstool update -t src
rosdep install --from-paths src --ignore-src --rosdistro `echo $ROS_DISTRO` -y
catkin build

# Install geographic-libs
wget https://raw.githubusercontent.com/mavlink/mavros/master/mavros/scripts/install_geographiclib_datasets.sh
sudo bash ./install_geographiclib_datasets.sh
rm ./install_geographiclib_datasets.sh

source ~/.bashrc

catkin build

echo "Reboot the system"
